### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by nikolaynesov** [cmgmyr/laravel-messenger-pusher-demo#4]
Does not work well. 

Some issues I faced with:
1) newMessagesCount -> newThreadsCount
2) `ErrorException in Thread.php line 299: implode(): Invalid arguments passed (View: messenger/resources/views/messenger/index.blade.php)`

**Comment by cmgmyr** [comment]
I will be updating this repo to Laravel 5.3 once it's released. It's very outdated ATM. refs #3
